// Location: Dfc.Desktop/Controls/PhotoUploadControl.axaml.cs
// Action: REPLACE entire file

using Avalonia;
using Avalonia.Controls;
using Avalonia.Input;
using Avalonia.Interactivity;
using Avalonia.Markup.Xaml;
using Avalonia.Media.Imaging;
using Avalonia.Platform.Storage;
using Dfc.Core.Services;
using System;
using System.Net.Http;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Dfc.Desktop.Controls;

public partial class PhotoUploadControl : UserControl
{
    private readonly string _photoCachePath;
    public static readonly StyledProperty<string?> PhotoUrlProperty =
        AvaloniaProperty.Register<PhotoUploadControl, string?>(nameof(PhotoUrl));

    public static readonly StyledProperty<IPhotoService?> PhotoServiceProperty =
        AvaloniaProperty.Register<PhotoUploadControl, IPhotoService?>(nameof(PhotoService));

    public string? PhotoUrl
    {
        get => GetValue(PhotoUrlProperty);
        set => SetValue(PhotoUrlProperty, value);
    }

    public IPhotoService? PhotoService
    {
        get => GetValue(PhotoServiceProperty);
        set => SetValue(PhotoServiceProperty, value);
    }

    public event EventHandler<string>? PhotoChanged;

    public PhotoUploadControl()
    {
        InitializeComponent();
        AddHandler(DragDrop.DropEvent, OnDrop);
        AddHandler(DragDrop.DragOverEvent, OnDragOver);

        // Initialize photo cache directory
        _photoCachePath = Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),
            "Desktop Food Cost",
            "PhotoCache"
        );
        Directory.CreateDirectory(_photoCachePath);
    }

    // This method is auto-generated by Avalonia when you build
    // It reads the XAML and wires up the controls
    private void InitializeComponent()
    {
        AvaloniaXamlLoader.Load(this);
    }

    protected override void OnPropertyChanged(AvaloniaPropertyChangedEventArgs change)
    {
        base.OnPropertyChanged(change);

        if (change.Property == PhotoUrlProperty)
        {
            _ = UpdatePreviewAsync();
        }
        else if (change.Property == PhotoServiceProperty)
        {
            _ = UpdatePreviewAsync(); // Also update preview when service is set
        }
    }

    private void OnDragOver(object? sender, DragEventArgs e)
    {
        if (e.Data.Contains(DataFormats.Files))
        {
            e.DragEffects = DragDropEffects.Copy;
            e.Handled = true;
        }
    }

    private async void OnDrop(object? sender, DragEventArgs e)
    {
        if (e.Data.Contains(DataFormats.Files))
        {
            var files = e.Data.GetFiles()?.ToList();
            if (files?.Count > 0)
            {
                var file = files[0];
                await UploadPhotoAsync(file.Path.LocalPath);
            }
        }
    }

    private async void OnBrowseClick(object? sender, RoutedEventArgs e)
    {
        var topLevel = TopLevel.GetTopLevel(this);
        if (topLevel == null) return;

        var files = await topLevel.StorageProvider.OpenFilePickerAsync(new FilePickerOpenOptions
        {
            Title = "Select Photo",
            AllowMultiple = false,
            FileTypeFilter = new[]
            {
                new FilePickerFileType("Image Files")
                {
                    Patterns = new[] { "*.jpg", "*.jpeg", "*.png" }
                }
            }
        });

        if (files.Count > 0)
        {
            await UploadPhotoAsync(files[0].Path.LocalPath);
        }
    }

    private async void OnRemoveClick(object? sender, RoutedEventArgs e)
    {
        if (!string.IsNullOrEmpty(PhotoUrl) && PhotoService != null)
        {
            await PhotoService.DeletePhotoAsync(PhotoUrl);
            PhotoUrl = null;
            PhotoChanged?.Invoke(this, string.Empty);
        }
    }

    private async Task UploadPhotoAsync(string sourceFilePath)
    {
        try
        {
            if (PhotoService == null)
                return;

            // Delete old photo if exists
            if (!string.IsNullOrEmpty(PhotoUrl))
            {
                await PhotoService.DeletePhotoAsync(PhotoUrl);
            }

            // Save new photo
            var newPhotoUrl = await PhotoService.SaveEntreePhotoAsync(sourceFilePath);
            PhotoUrl = newPhotoUrl;
            PhotoChanged?.Invoke(this, newPhotoUrl);
        }
        catch
        {
            // TODO: Show error to user
        }
    }

    private async Task UpdatePreviewAsync()
    {
        var previewImage = this.FindControl<Image>("PreviewImage");
        var dropZone = this.FindControl<Border>("DropZone");
        var removeButton = this.FindControl<Button>("RemoveButton");

        if (previewImage == null || dropZone == null || removeButton == null)
            return;

        if (!string.IsNullOrEmpty(PhotoUrl) && PhotoService != null)
        {
            try
            {
                // Check if it's a Supabase URL
                if (PhotoUrl.Contains("supabase.co") || PhotoUrl.Contains("/storage/v1/object/public/"))
                {
                    // Generate cache file path from URL
                    var cacheFileName = GenerateCacheFileName(PhotoUrl);
                    var cachedPhotoPath = Path.Combine(_photoCachePath, cacheFileName);

                    // Check if photo exists in cache
                    if (File.Exists(cachedPhotoPath))
                    {
                        // Load from cache
                        System.Diagnostics.Debug.WriteLine($"[PhotoPreview] ✓ Loading photo from cache: {cachedPhotoPath}");
                        previewImage.Source = new Bitmap(cachedPhotoPath);
                        previewImage.IsVisible = true;
                        dropZone.IsVisible = false;
                        removeButton.IsVisible = true;
                    }
                    else
                    {
                        // Download from Supabase and cache
                        System.Diagnostics.Debug.WriteLine($"[PhotoPreview] Downloading photo from Supabase: {PhotoUrl}");
                        using var httpClient = new HttpClient();
                        var photoBytes = await httpClient.GetByteArrayAsync(PhotoUrl);
                        
                        // Save to cache
                        await File.WriteAllBytesAsync(cachedPhotoPath, photoBytes);
                        System.Diagnostics.Debug.WriteLine($"[PhotoPreview] ✓ Photo cached to: {cachedPhotoPath}");

                        // Load from cache
                        previewImage.Source = new Bitmap(cachedPhotoPath);
                        previewImage.IsVisible = true;
                        dropZone.IsVisible = false;
                        removeButton.IsVisible = true;
                    }
                }
                else
                {
                    // Local file path
                    var fullPath = PhotoService.GetPhotoFullPath(PhotoUrl);

                    if (File.Exists(fullPath))
                    {
                        previewImage.Source = new Bitmap(fullPath);
                        previewImage.IsVisible = true;
                        dropZone.IsVisible = false;
                        removeButton.IsVisible = true;
                        System.Diagnostics.Debug.WriteLine($"[PhotoPreview] ✓ Photo loaded from local: {fullPath}");
                    }
                    else
                    {
                        System.Diagnostics.Debug.WriteLine($"[PhotoPreview] ✗ Local file not found: {fullPath}");
                        previewImage.IsVisible = false;
                        dropZone.IsVisible = true;
                        removeButton.IsVisible = false;
                    }
                }
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"[PhotoPreview] ✗ Failed to load photo: {ex.Message}");
                previewImage.IsVisible = false;
                dropZone.IsVisible = true;
                removeButton.IsVisible = false;
            }
        }
        else
        {
            previewImage.IsVisible = false;
            dropZone.IsVisible = true;
            removeButton.IsVisible = false;
        }
    }

    private string GenerateCacheFileName(string photoUrl)
    {
        // Extract filename from Supabase URL
        // Example: https://.../photos/Entree/abc-123/photo.jpg -> Entree_abc-123_photo.jpg
        try
        {
            var uri = new Uri(photoUrl);
            var pathParts = uri.LocalPath.Split('/');
            
            // Find "photos" in path and take everything after it
            var photosIndex = Array.IndexOf(pathParts, "photos");
            if (photosIndex >= 0 && photosIndex < pathParts.Length - 1)
            {
                var relevantParts = pathParts.Skip(photosIndex + 1).ToArray();
                return string.Join("_", relevantParts);
            }
            
            // Fallback: use hash of URL
            return $"photo_{photoUrl.GetHashCode():X}.jpg";
        }
        catch
        {
            // Fallback: use hash of URL
            return $"photo_{photoUrl.GetHashCode():X}.jpg";
        }
    }
}