// <auto-generated />
using System;
using Dfc.Data.LocalDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dfc.Data.Migrations
{
    [DbContext(typeof(DfcDbContext))]
    [Migration("20251007075050_AddCaseQuantityToIngredient")]
    partial class AddCaseQuantityToIngredient
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("Dfc.Core.Models.Allergen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("Allergens");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 10, 7, 7, 50, 50, 351, DateTimeKind.Utc).AddTicks(4135),
                            ModifiedAt = new DateTime(2025, 10, 7, 7, 50, 50, 351, DateTimeKind.Utc).AddTicks(4136),
                            Name = "Milk",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 10, 7, 7, 50, 50, 351, DateTimeKind.Utc).AddTicks(4149),
                            ModifiedAt = new DateTime(2025, 10, 7, 7, 50, 50, 351, DateTimeKind.Utc).AddTicks(4150),
                            Name = "Eggs",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2025, 10, 7, 7, 50, 50, 351, DateTimeKind.Utc).AddTicks(4153),
                            ModifiedAt = new DateTime(2025, 10, 7, 7, 50, 50, 351, DateTimeKind.Utc).AddTicks(4153),
                            Name = "Fish",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2025, 10, 7, 7, 50, 50, 351, DateTimeKind.Utc).AddTicks(4161),
                            ModifiedAt = new DateTime(2025, 10, 7, 7, 50, 50, 351, DateTimeKind.Utc).AddTicks(4161),
                            Name = "Shellfish",
                            Type = 3
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2025, 10, 7, 7, 50, 50, 351, DateTimeKind.Utc).AddTicks(4163),
                            ModifiedAt = new DateTime(2025, 10, 7, 7, 50, 50, 351, DateTimeKind.Utc).AddTicks(4164),
                            Name = "Tree Nuts",
                            Type = 4
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTime(2025, 10, 7, 7, 50, 50, 351, DateTimeKind.Utc).AddTicks(4167),
                            ModifiedAt = new DateTime(2025, 10, 7, 7, 50, 50, 351, DateTimeKind.Utc).AddTicks(4167),
                            Name = "Peanuts",
                            Type = 5
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            CreatedAt = new DateTime(2025, 10, 7, 7, 50, 50, 351, DateTimeKind.Utc).AddTicks(4169),
                            ModifiedAt = new DateTime(2025, 10, 7, 7, 50, 50, 351, DateTimeKind.Utc).AddTicks(4169),
                            Name = "Wheat",
                            Type = 6
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            CreatedAt = new DateTime(2025, 10, 7, 7, 50, 50, 351, DateTimeKind.Utc).AddTicks(4171),
                            ModifiedAt = new DateTime(2025, 10, 7, 7, 50, 50, 351, DateTimeKind.Utc).AddTicks(4171),
                            Name = "Soybeans",
                            Type = 7
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            CreatedAt = new DateTime(2025, 10, 7, 7, 50, 50, 351, DateTimeKind.Utc).AddTicks(4177),
                            ModifiedAt = new DateTime(2025, 10, 7, 7, 50, 50, 351, DateTimeKind.Utc).AddTicks(4178),
                            Name = "Sesame",
                            Type = 8
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2025, 10, 7, 7, 50, 50, 351, DateTimeKind.Utc).AddTicks(4180),
                            ModifiedAt = new DateTime(2025, 10, 7, 7, 50, 50, 351, DateTimeKind.Utc).AddTicks(4180),
                            Name = "Vegan",
                            Type = 9
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2025, 10, 7, 7, 50, 50, 351, DateTimeKind.Utc).AddTicks(4183),
                            ModifiedAt = new DateTime(2025, 10, 7, 7, 50, 50, 351, DateTimeKind.Utc).AddTicks(4183),
                            Name = "Vegetarian",
                            Type = 10
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2025, 10, 7, 7, 50, 50, 351, DateTimeKind.Utc).AddTicks(4187),
                            ModifiedAt = new DateTime(2025, 10, 7, 7, 50, 50, 351, DateTimeKind.Utc).AddTicks(4188),
                            Name = "Pescatarian",
                            Type = 11
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            CreatedAt = new DateTime(2025, 10, 7, 7, 50, 50, 351, DateTimeKind.Utc).AddTicks(4190),
                            ModifiedAt = new DateTime(2025, 10, 7, 7, 50, 50, 351, DateTimeKind.Utc).AddTicks(4190),
                            Name = "Gluten Free",
                            Type = 12
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreatedAt = new DateTime(2025, 10, 7, 7, 50, 50, 351, DateTimeKind.Utc).AddTicks(4192),
                            ModifiedAt = new DateTime(2025, 10, 7, 7, 50, 50, 351, DateTimeKind.Utc).AddTicks(4192),
                            Name = "Kosher",
                            Type = 13
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            CreatedAt = new DateTime(2025, 10, 7, 7, 50, 50, 351, DateTimeKind.Utc).AddTicks(4194),
                            ModifiedAt = new DateTime(2025, 10, 7, 7, 50, 50, 351, DateTimeKind.Utc).AddTicks(4194),
                            Name = "Halal",
                            Type = 14
                        },
                        new
                        {
                            Id = new Guid("12121212-1212-1212-1212-121212121212"),
                            CreatedAt = new DateTime(2025, 10, 7, 7, 50, 50, 351, DateTimeKind.Utc).AddTicks(4196),
                            ModifiedAt = new DateTime(2025, 10, 7, 7, 50, 50, 351, DateTimeKind.Utc).AddTicks(4196),
                            Name = "Contains Alcohol",
                            Type = 15
                        },
                        new
                        {
                            Id = new Guid("13131313-1313-1313-1313-131313131313"),
                            CreatedAt = new DateTime(2025, 10, 7, 7, 50, 50, 351, DateTimeKind.Utc).AddTicks(4198),
                            ModifiedAt = new DateTime(2025, 10, 7, 7, 50, 50, 351, DateTimeKind.Utc).AddTicks(4198),
                            Name = "Nightshades",
                            Type = 16
                        },
                        new
                        {
                            Id = new Guid("14141414-1414-1414-1414-141414141414"),
                            CreatedAt = new DateTime(2025, 10, 7, 7, 50, 50, 351, DateTimeKind.Utc).AddTicks(4201),
                            ModifiedAt = new DateTime(2025, 10, 7, 7, 50, 50, 351, DateTimeKind.Utc).AddTicks(4201),
                            Name = "Sulfites",
                            Type = 17
                        },
                        new
                        {
                            Id = new Guid("15151515-1515-1515-1515-151515151515"),
                            CreatedAt = new DateTime(2025, 10, 7, 7, 50, 50, 351, DateTimeKind.Utc).AddTicks(4203),
                            ModifiedAt = new DateTime(2025, 10, 7, 7, 50, 50, 351, DateTimeKind.Utc).AddTicks(4203),
                            Name = "Added Sugar",
                            Type = 18
                        });
                });

            modelBuilder.Entity("Dfc.Core.Models.Entree", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MenuPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlatingEquipment")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("Name");

                    b.ToTable("Entrees");
                });

            modelBuilder.Entity("Dfc.Core.Models.EntreeAllergen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AllergenId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntreeId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAutoDetected")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceIngredients")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AllergenId");

                    b.HasIndex("EntreeId", "AllergenId")
                        .IsUnique();

                    b.ToTable("EntreeAllergens");
                });

            modelBuilder.Entity("Dfc.Core.Models.EntreeIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntreeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("Unit")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EntreeId");

                    b.HasIndex("IngredientId");

                    b.ToTable("EntreeIngredients");
                });

            modelBuilder.Entity("Dfc.Core.Models.EntreeRecipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntreeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Unit")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EntreeId");

                    b.HasIndex("RecipeId");

                    b.ToTable("EntreeRecipes");
                });

            modelBuilder.Entity("Dfc.Core.Models.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AlternateConversionQuantity")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AlternateConversionUnit")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AlternateUnit")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CaseQuantity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentPrice")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Unit")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseAlternateUnit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VendorName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("VendorSku")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("LocationId", "Name");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("Dfc.Core.Models.IngredientAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AliasName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AliasName");

                    b.HasIndex("IngredientId");

                    b.ToTable("IngredientAliases");
                });

            modelBuilder.Entity("Dfc.Core.Models.IngredientAllergen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AllergenId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAutoDetected")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceIngredients")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AllergenId");

                    b.HasIndex("IngredientId", "AllergenId")
                        .IsUnique();

                    b.ToTable("IngredientAllergens");
                });

            modelBuilder.Entity("Dfc.Core.Models.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Dfc.Core.Models.PriceHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AggregationType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAggregated")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecordedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId", "RecordedDate");

                    b.ToTable("PriceHistories");
                });

            modelBuilder.Entity("Dfc.Core.Models.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructions")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsShared")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PrepTimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Yield")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("YieldUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("LocationId", "Name");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("Dfc.Core.Models.RecipeAllergen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AllergenId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAutoDetected")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceIngredients")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AllergenId");

                    b.HasIndex("RecipeId", "AllergenId")
                        .IsUnique();

                    b.ToTable("RecipeAllergens");
                });

            modelBuilder.Entity("Dfc.Core.Models.RecipeIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayText")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Unit")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("Dfc.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("SupabaseAuthUid")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SupabaseAuthUid");

                    b.HasIndex("LocationId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Dfc.Core.Models.Entree", b =>
                {
                    b.HasOne("Dfc.Core.Models.Location", "Location")
                        .WithMany("Entrees")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Dfc.Core.Models.EntreeAllergen", b =>
                {
                    b.HasOne("Dfc.Core.Models.Allergen", "Allergen")
                        .WithMany("EntreeAllergens")
                        .HasForeignKey("AllergenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dfc.Core.Models.Entree", "Entree")
                        .WithMany("EntreeAllergens")
                        .HasForeignKey("EntreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allergen");

                    b.Navigation("Entree");
                });

            modelBuilder.Entity("Dfc.Core.Models.EntreeIngredient", b =>
                {
                    b.HasOne("Dfc.Core.Models.Entree", "Entree")
                        .WithMany("EntreeIngredients")
                        .HasForeignKey("EntreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dfc.Core.Models.Ingredient", "Ingredient")
                        .WithMany("EntreeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entree");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("Dfc.Core.Models.EntreeRecipe", b =>
                {
                    b.HasOne("Dfc.Core.Models.Entree", "Entree")
                        .WithMany("EntreeRecipes")
                        .HasForeignKey("EntreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dfc.Core.Models.Recipe", "Recipe")
                        .WithMany("EntreeRecipes")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entree");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Dfc.Core.Models.Ingredient", b =>
                {
                    b.HasOne("Dfc.Core.Models.Location", "Location")
                        .WithMany("Ingredients")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Dfc.Core.Models.IngredientAlias", b =>
                {
                    b.HasOne("Dfc.Core.Models.Ingredient", "Ingredient")
                        .WithMany("Aliases")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("Dfc.Core.Models.IngredientAllergen", b =>
                {
                    b.HasOne("Dfc.Core.Models.Allergen", "Allergen")
                        .WithMany()
                        .HasForeignKey("AllergenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dfc.Core.Models.Ingredient", "Ingredient")
                        .WithMany("IngredientAllergens")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allergen");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("Dfc.Core.Models.PriceHistory", b =>
                {
                    b.HasOne("Dfc.Core.Models.Ingredient", "Ingredient")
                        .WithMany("PriceHistory")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("Dfc.Core.Models.Recipe", b =>
                {
                    b.HasOne("Dfc.Core.Models.Location", "Location")
                        .WithMany("Recipes")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Dfc.Core.Models.RecipeAllergen", b =>
                {
                    b.HasOne("Dfc.Core.Models.Allergen", "Allergen")
                        .WithMany("RecipeAllergens")
                        .HasForeignKey("AllergenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dfc.Core.Models.Recipe", "Recipe")
                        .WithMany("RecipeAllergens")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allergen");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Dfc.Core.Models.RecipeIngredient", b =>
                {
                    b.HasOne("Dfc.Core.Models.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dfc.Core.Models.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Dfc.Core.Models.User", b =>
                {
                    b.HasOne("Dfc.Core.Models.Location", "Location")
                        .WithMany("Users")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Dfc.Core.Models.Allergen", b =>
                {
                    b.Navigation("EntreeAllergens");

                    b.Navigation("RecipeAllergens");
                });

            modelBuilder.Entity("Dfc.Core.Models.Entree", b =>
                {
                    b.Navigation("EntreeAllergens");

                    b.Navigation("EntreeIngredients");

                    b.Navigation("EntreeRecipes");
                });

            modelBuilder.Entity("Dfc.Core.Models.Ingredient", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("EntreeIngredients");

                    b.Navigation("IngredientAllergens");

                    b.Navigation("PriceHistory");

                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("Dfc.Core.Models.Location", b =>
                {
                    b.Navigation("Entrees");

                    b.Navigation("Ingredients");

                    b.Navigation("Recipes");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Dfc.Core.Models.Recipe", b =>
                {
                    b.Navigation("EntreeRecipes");

                    b.Navigation("RecipeAllergens");

                    b.Navigation("RecipeIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
